const savedProfile = JSON.parse(localStorage.getItem('deskos-profile') || 'null');
if (!savedProfile) window.location.replace('login.html');
if (savedProfile) {
  document.documentElement.dataset.theme = savedProfile.theme || 'lime';
  const initials = savedProfile.name.split(' ').map(part => part[0]).join('').slice(0, 2).toUpperCase();
  document.querySelectorAll('[data-user-full-name]').forEach(el => el.textContent = savedProfile.name);
  document.querySelectorAll('[data-user-initials]').forEach(el => el.textContent = initials);
}
const query = new URLSearchParams(window.location.search);
const view = query.get('view') || 'tasks';
const app = query.get('app') || 'Figma';
const file = query.get('name') || 'Q3 Product Roadmap';
const fileId = query.get('file');
const state = window.DeskOS;
const renderClock = () => { const now = new Date(); document.querySelector('#liveClock').textContent = new Intl.DateTimeFormat(undefined, { hour:'numeric', minute:'2-digit' }).format(now); };
renderClock(); setInterval(renderClock, 60000);
const host = document.querySelector('#hubContent');
const toast = (message) => { const box = document.querySelector('#toast'); box.textContent = message; box.classList.add('show'); clearTimeout(window.toastTimer); window.toastTimer = setTimeout(() => box.classList.remove('show'), 1900); };
const shell = (eyebrow, title, subhead, body) => `<div class="page-heading hub-heading"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="subhead">${subhead}</p></div><a class="back-link" href="index.html">← Overview</a></div>${body}`;
const taskRow = (task) => `<div class="task-edit-row ${task.complete ? 'complete' : ''}"><button class="row-check" data-task-action="toggle" data-id="${task.id}">${task.complete ? '✓' : ''}</button><span><b>${task.title}</b><small>${task.due}</small></span><button data-task-action="edit" data-id="${task.id}">Edit</button><button class="danger-text" data-task-action="delete" data-id="${task.id}">Delete</button></div>`;
const tasks = () => shell('MY TASKS', 'A little progress, every day.', `${state.incompleteTasks().length} unfinished tasks are ready when you are.`, `<section class="wide-card"><form class="task-create-form" id="taskCreateForm"><input id="newTaskTitle" placeholder="Add a task…" maxlength="80" required><input id="newTaskDue" placeholder="Time (e.g. 14:00)"><button class="new-button add-inline">+ Add task</button></form><div class="full-task-list" id="fullTaskList">${state.state.tasks.map(taskRow).join('') || '<p class="empty-copy">No tasks yet. Add one above.</p>'}</div></section>`);
const calendar = () => { const now = new Date(); return shell('CALENDAR', 'Your week, in rhythm.', new Intl.DateTimeFormat(undefined, { month:'long', year:'numeric' }).format(now), `<section class="wide-card calendar-page"><div class="month-heading"><button disabled>←</button><h2>${new Intl.DateTimeFormat(undefined, { month:'long', year:'numeric' }).format(now)}</h2><button disabled>→</button></div><div class="big-calendar" id="bigCalendar"></div><div class="agenda"><div class="agenda-title"><p class="section-title">TODAY'S EVENTS</p><button class="text-action" id="addEvent">+ Add</button></div><div id="agendaList"></div></div></section>`); };
const notes = () => { const note = state.state.notes[0]; return shell('NOTES', 'Ideas need a home.', `${state.state.notes.length} notes saved locally in DeskOS.`, `<section class="notes-layout"><aside class="note-list"><button class="new-button add-inline" id="newNote">+ New note</button><div id="noteList">${state.state.notes.map((item, index) => `<button class="note-item ${index === 0 ? 'active' : ''}" data-note-id="${item.id}"><b>${item.title}</b><small>${state.relativeTime(item.updatedAt)}</small></button>`).join('')}</div></aside><article class="wide-card note-editor"><div><p class="section-title">PERSONAL NOTE</p><input id="noteTitle" value="${note?.title || ''}" placeholder="Note title"><span class="editor-save" id="editorSave">SAVED</span></div><textarea id="noteEditor" placeholder="Start writing…">${note?.content || ''}</textarea><footer><button class="danger-text" id="deleteNote">Delete note</button><span>Saved on this device</span></footer></article></section>`); };
const files = () => shell('FILES', 'Your recent work.', 'Recent means what you opened in DeskOS — not files from your whole computer.', `<section class="wide-card files-page"><div class="list-toolbar"><div class="tabs"><button class="selected">Recent</button><button>Shared with me</button><button>Starred</button></div><label class="new-button add-inline file-upload">+ Add local file<input id="localFileInput" type="file" multiple></label></div><div class="file-table"><div class="file-head"><span>Name</span><span>Source</span><span>Opened</span></div>${[...state.state.files].sort((a,b) => b.openedAt-a.openedAt).map(item => `<a href="hub.html?view=file&file=${item.id}" data-open-file="${item.id}" class="file-table-row"><span><i class="file-icon ${item.kind}">▱</i><b>${item.name}</b></span><span>${item.source}</span><span>${state.relativeTime(item.openedAt)} <em>↗</em></span></a>`).join('')}</div></section>`);
const project = (kind) => { const pin = state.state.pins[kind]; return shell('PINNED SPACE', pin.title, pin.description, `<section class="project-grid"><article class="wide-card project-summary"><span class="dot ${pin.colour}"></span><h2>${pin.title}</h2><p>Custom pinned space · Updated today</p><div class="project-progress"><i style="width:68%"></i></div><small>Made for your workflow</small></article><article class="wide-card pin-editor"><p class="section-title">EDIT THIS SPACE</p><label>Name<input id="pinTitle" value="${pin.title}" maxlength="32"></label><label>Description<textarea id="pinDescription" maxlength="120">${pin.description}</textarea></label><button class="new-button add-inline" id="savePin">Save changes</button></article></section>`); };
const focus = () => shell('FOCUS', 'Make room for deep work.', 'Pick a task, set a timer, and let the world wait.', `<section class="focus-page"><article class="wide-card focus-large"><p class="section-title">FOCUS SESSION</p><div class="large-timer"><strong id="focusClock">25:00</strong><span>FOCUS</span></div><h2 id="focusMessage">One thing at a time.</h2><button class="new-button focus-start" data-action="focus">▶ Start a session</button></article><article class="wide-card session-list"><p class="section-title">TODAY'S SESSIONS</p><h2>1 of 4 complete</h2><div>09:00 <b>Homepage review</b> <span>25 min</span></div><div>Next <b>Investor update</b> <span>25 min</span></div></article></section>`);
const weather = () => shell('LOCAL WEATHER', `Checking ${savedProfile?.location || 'your location'}…`, 'Live conditions update when you are online.', `<section class="wide-card weather-page" id="weatherPage"><div class="sun-icon"><span></span></div><strong id="pageWeatherTemp">—°</strong><div><h2 id="pageWeatherLabel">Loading weather…</h2><p id="pageWeatherDetail">Getting current conditions</p></div><div class="forecast"><span>LIVE <b id="pageWeatherWind">—</b></span><span>HUMIDITY <b id="pageWeatherHumidity">—</b></span><span>UV <b id="pageWeatherUv">—</b></span></div></section>`);
const wellbeing = () => { const [hours, minutes] = state.activityLabel().split(' '); return shell('DIGITAL WELLBEING', 'Your DeskOS time.', 'This reflects time spent active in DeskOS — browsers cannot access your computer-wide screen time.', `<section class="wide-card wellbeing-page"><div class="wellbeing-stat"><strong>${hours}<sup>h</sup> ${minutes.replace('m','')}<sup>m</sup></strong><span>active in DeskOS today</span><em>● local activity tracker</em></div><div class="large-bars">${[42,68,50,86,57,36,30].map((n,i) => `<div><i class="${i === 3 ? 'current' : ''}" style="height:${n}%"></i><span>${'MTWTFSS'[i]}</span></div>`).join('')}</div></section>`); };
const apps = () => shell('QUICK LAUNCH', 'Your everyday tools.', 'Keep the things you use most within reach.', `<section class="wide-card app-page"><div class="app-grid large">${['Figma','Notion','Slack','Mail','Drive'].map((name,i) => `<a href="hub.html?view=app&app=${name}" class="app-tile"><span class="app-icon ${['figma','notion','slack','mail','drive'][i]}">${name[0]}</span><b>${name}</b></a>`).join('')}<button class="app-tile add-app" data-action="add-app"><span>+</span><b>Add app</b></button></div></section>`);
const appPage = () => shell('QUICK APP', app, `${app} is ready when you are.`, `<section class="wide-card app-detail"><div class="app-icon figma">${app[0]}</div><div><p class="section-title">CONNECTED TOOL</p><h2>${app}</h2><p>Open a fresh workspace or pick up where you left off.</p><button class="new-button add-inline" data-action="launch">Launch ${app}</button></div></section>`);
const filePage = () => { const item = state.state.files.find(entry => entry.id === fileId) || { name: file, source: 'DeskOS', openedAt: Date.now() }; return shell('RECENT FILE', item.name, `Opened ${state.relativeTime(item.openedAt)} in ${item.source}.`, `<section class="wide-card document-page"><header><p class="section-title">DESKOS FILE RECORD</p><div><button class="new-button add-inline" data-action="share">Share</button>${fileId ? `<button class="delete-file" data-delete-file="${fileId}">Remove</button>` : ''}</div></header><h2>${item.name}</h2><p>DeskOS records this file in your local recent list. To open the source document itself, use its original app or your file manager.</p><div class="document-lines"><i></i><i></i><i></i><i></i><i></i></div></section>`); };
const utility = (type) => { const initials = savedProfile?.name.split(' ').map(part => part[0]).join('').slice(0, 2).toUpperCase() || 'AM'; const data = {new:['CREATE','What would you like to make?','Start small. You can shape it as you go.',`<section class="create-grid"><button data-action="created"><span>✓</span><b>New task</b><small>Capture an action</small></button><button data-action="created"><span>✦</span><b>New note</b><small>Write something down</small></button><button data-action="created"><span>□</span><b>New event</b><small>Set aside time</small></button></section>`],search:['SEARCH','Find your flow.','Search across tasks, notes and files.',`<section class="wide-card search-page"><label>⌕<input id="searchInput" autofocus placeholder="Try workshop, roadmap, or ideas"></label><div id="searchResults"><p>Start typing to search your DeskOS space.</p></div></section>`],notifications:['NOTIFICATIONS','You’re all caught up.','Nothing needs your attention right now.',`<section class="wide-card empty-state"><span>✦</span><h2>A quiet inbox.</h2><p>We’ll keep important updates here.</p></section>`],profile:['YOUR ACCOUNT',savedProfile?.name || 'Alex Morgan','Update the colours and details that make DeskOS yours.',`<section class="personalise-card wide-card"><div class="avatar large-avatar">${initials}</div><div class="personalise-fields"><label>Your name<input id="profileName" value="${savedProfile?.name || ''}" maxlength="24"></label><label>Your city<input id="profileLocation" value="${savedProfile?.location || 'Sydney'}" maxlength="32"></label></div><div class="theme-picker"><p class="section-title">DESK COLOUR</p><div><button class="theme-dot lime-dot" data-theme="lime" aria-label="Fresh lime"></button><button class="theme-dot lavender-dot" data-theme="lavender" aria-label="Soft lilac"></button><button class="theme-dot peach-dot" data-theme="peach" aria-label="Warm peach"></button><button class="theme-dot sky-dot" data-theme="sky" aria-label="Clear blue"></button></div></div><button class="new-button add-inline" data-action="save-profile">Save changes</button></section>`],help:['HELP & SHORTCUTS','A few useful keys.','DeskOS is designed to stay out of your way.',`<section class="wide-card shortcut-page"><div><kbd>⌘ K</kbd><span>Search DeskOS</span></div><div><kbd>⌘ ↵</kbd><span>Save a note</span></div><div><kbd>?</kbd><span>Open help and shortcuts</span></div></section>`]}[type]; return shell(...data); };
const pages = {tasks,calendar,notes,files,product:() => project('product'),personal:() => project('personal'),reading:() => project('reading'),focus,weather,wellbeing,apps,app:appPage,file:filePage,new:() => utility('new'),search:() => utility('search'),notifications:() => utility('notifications'),profile:() => utility('profile'),help:() => utility('help')};
host.innerHTML = (pages[view] || tasks)();
document.title = `${host.querySelector('h1').textContent} — DeskOS`;
document.querySelector(`[data-nav="${view}"]`)?.classList.add('active');
document.querySelector(`[data-theme="${document.documentElement.dataset.theme || 'lime'}"]`)?.classList.add('selected');
document.querySelectorAll('.nav-count').forEach(el => el.textContent = state.incompleteTasks().length);
Object.entries(state.state.pins).forEach(([key, pin]) => { const target = document.querySelector(`[data-pin-name="${key}"]`); if (target) target.textContent = pin.title; });
const escapeText = (value) => String(value).replace(/[&<>"']/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' })[char]);

if (view === 'tasks') {
  document.querySelector('#taskCreateForm').addEventListener('submit', event => { event.preventDefault(); const title = document.querySelector('#newTaskTitle').value.trim(); if (!title) return; state.addTask(title, document.querySelector('#newTaskDue').value.trim() || 'Today'); window.location.reload(); });
  document.querySelector('#fullTaskList').addEventListener('click', event => { const button = event.target.closest('[data-task-action]'); if (!button) return; const task = state.state.tasks.find(item => item.id === button.dataset.id); if (!task) return; if (button.dataset.taskAction === 'toggle') state.updateTask(task.id, { complete: !task.complete }); if (button.dataset.taskAction === 'edit') { const title = window.prompt('Edit task', task.title); const due = title !== null ? window.prompt('Time or label', task.due) : null; if (title?.trim()) state.updateTask(task.id, { title: title.trim(), due: due?.trim() || 'Today' }); } if (button.dataset.taskAction === 'delete' && window.confirm(`Delete “${task.title}”?`)) state.deleteTask(task.id); window.location.reload(); });
}

if (view === 'calendar') {
  const now = new Date(); const grid = document.querySelector('#bigCalendar'); const year = now.getFullYear(); const month = now.getMonth(); const offset = (new Date(year, month, 1).getDay() + 6) % 7;
  grid.innerHTML = ['MON','TUE','WED','THU','FRI','SAT','SUN'].map(day => `<b>${day}</b>`).join('') + Array.from({ length: offset }, () => '<span></span>').join('') + Array.from({ length: new Date(year, month + 1, 0).getDate() }, (_, index) => `<button class="${index + 1 === now.getDate() ? 'today' : ''}">${index + 1}</button>`).join('');
  const today = now.toISOString().slice(0, 10); const agenda = document.querySelector('#agendaList'); const renderAgenda = () => { const events = state.state.events.filter(event => event.date === today).sort((a,b) => a.time.localeCompare(b.time)); agenda.innerHTML = events.length ? events.map(event => `<div><time>${event.time}</time><i class="${event.colour}"></i><span><b>${event.title}</b><small>${event.detail}</small></span><button class="danger-text" data-event-id="${event.id}">×</button></div>`).join('') : '<p class="empty-copy">No events today.</p>'; };
  renderAgenda(); document.querySelector('#addEvent').addEventListener('click', () => { const title = window.prompt('Event name'); if (!title?.trim()) return; const time = window.prompt('Time (24-hour)', '09:00') || '09:00'; state.addEvent(title.trim(), today, time); renderAgenda(); }); agenda.addEventListener('click', event => { const button = event.target.closest('[data-event-id]'); if (button && window.confirm('Delete this event?')) { state.deleteEvent(button.dataset.eventId); renderAgenda(); } });
}

if (view === 'notes') {
  let activeNote = state.state.notes[0]; const title = document.querySelector('#noteTitle'); const editor = document.querySelector('#noteEditor'); const save = () => { if (!activeNote) return; document.querySelector('#editorSave').textContent = 'SAVING'; clearTimeout(window.noteTimer); window.noteTimer = setTimeout(() => { state.updateNote(activeNote.id, { title: title.value.trim() || 'Untitled note', content: editor.value }); document.querySelector('#editorSave').textContent = 'SAVED'; }, 350); };
  document.querySelector('#noteList').addEventListener('click', event => { const item = event.target.closest('[data-note-id]'); if (!item) return; save(); activeNote = state.state.notes.find(note => note.id === item.dataset.noteId); title.value = activeNote.title; editor.value = activeNote.content; document.querySelectorAll('.note-item').forEach(note => note.classList.toggle('active', note === item)); });
  document.querySelector('#newNote').addEventListener('click', () => { state.addNote('Untitled note'); window.location.reload(); }); title.addEventListener('input', save); editor.addEventListener('input', save); document.querySelector('#deleteNote').addEventListener('click', () => { if (activeNote && window.confirm(`Delete “${activeNote.title}”?`)) { state.deleteNote(activeNote.id); window.location.reload(); } });
}

if (view === 'files') {
  document.querySelector('#localFileInput').addEventListener('change', event => { [...event.target.files].forEach(file => state.addFile(file.name, 'Local file')); window.location.reload(); });
  document.querySelectorAll('[data-open-file]').forEach(link => link.addEventListener('click', () => state.openFile(link.dataset.openFile)));
}
if (view === 'file' && fileId) state.openFile(fileId);
document.querySelector('[data-delete-file]')?.addEventListener('click', event => { const id = event.currentTarget.dataset.deleteFile; const item = state.state.files.find(file => file.id === id); if (item && window.confirm(`Remove “${item.name}” from DeskOS recent files?`)) { state.state.files = state.state.files.filter(file => file.id !== id); state.save(); window.location.href = 'hub.html?view=files'; } });
if (['product','personal','reading'].includes(view)) document.querySelector('#savePin').addEventListener('click', () => { state.updatePin(view, { title: document.querySelector('#pinTitle').value.trim() || 'Untitled space', description: document.querySelector('#pinDescription').value.trim() || 'A personalised DeskOS space.' }); toast('Pinned space saved'); setTimeout(() => window.location.reload(), 450); });

if (view === 'weather') {
  const describe = (code) => ({ 0:'Clear skies', 1:'Mostly clear', 2:'Partly cloudy', 3:'Overcast', 45:'Foggy', 51:'Light drizzle', 61:'Rainy', 63:'Rainy', 71:'Snowy', 80:'Showers', 95:'Stormy' }[code] || 'Local conditions');
  (async () => { try { const place = await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(savedProfile.location || 'Sydney')}&count=1&language=en&format=json`).then(res => res.json()); const location = place.results?.[0]; if (!location) throw new Error('No location'); const data = await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${location.latitude}&longitude=${location.longitude}&current=temperature_2m,apparent_temperature,relative_humidity_2m,weather_code,wind_speed_10m&daily=uv_index_max&timezone=auto`).then(res => res.json()); const weather = data.current; document.querySelector('#pageWeatherTemp').textContent = `${Math.round(weather.temperature_2m)}°`; document.querySelector('#pageWeatherLabel').textContent = describe(weather.weather_code); document.querySelector('#pageWeatherDetail').textContent = `${location.name} · Feels like ${Math.round(weather.apparent_temperature)}°`; document.querySelector('#pageWeatherWind').textContent = `${Math.round(weather.wind_speed_10m)} km/h`; document.querySelector('#pageWeatherHumidity').textContent = `${weather.relative_humidity_2m}%`; document.querySelector('#pageWeatherUv').textContent = Math.round(data.daily.uv_index_max?.[0] || 0); } catch { document.querySelector('#pageWeatherLabel').textContent = 'Weather unavailable'; document.querySelector('#pageWeatherDetail').textContent = 'Check your internet connection.'; } })();
}

document.querySelector('#searchInput')?.addEventListener('input', event => { const needle = event.target.value.toLowerCase(); const matches = [...state.state.tasks.map(item => ({ label:item.title, type:'Task', href:'hub.html?view=tasks' })), ...state.state.notes.map(item => ({ label:item.title, type:'Note', href:'hub.html?view=notes' })), ...state.state.files.map(item => ({ label:item.name, type:'File', href:`hub.html?view=file&file=${item.id}` }))].filter(item => item.label.toLowerCase().includes(needle)); document.querySelector('#searchResults').innerHTML = needle ? (matches.length ? matches.map(item => `<a href="${item.href}"><b>${escapeText(item.label)}</b><span>${item.type}</span></a>`).join('') : '<p>No matches yet.</p>') : '<p>Start typing to search your DeskOS space.</p>'; });
document.querySelectorAll('[data-action]').forEach(button => button.addEventListener('click', event => { const action = event.currentTarget.dataset.action; if (action === 'focus') { let seconds = 1500; event.currentTarget.textContent = 'Ⅱ Session in progress'; event.currentTarget.disabled = true; document.querySelector('#focusMessage').textContent = 'You’re in the zone.'; window.focusTimer = setInterval(() => { seconds -= 1; document.querySelector('#focusClock').textContent = `${String(Math.floor(seconds / 60)).padStart(2,'0')}:${String(seconds % 60).padStart(2,'0')}`; if (!seconds) clearInterval(window.focusTimer); }, 1000); return; } toast(action === 'launch' ? `${app} is ready to launch` : 'Done — your space is updated'); }));
document.querySelectorAll('[data-theme]').forEach(button => button.addEventListener('click', () => { document.documentElement.dataset.theme = button.dataset.theme; document.querySelectorAll('[data-theme]').forEach(dot => dot.classList.toggle('selected', dot === button)); }));
document.querySelector('[data-action="save-profile"]')?.addEventListener('click', () => { const name = document.querySelector('#profileName').value.trim(); const location = document.querySelector('#profileLocation').value.trim(); if (!name) return toast('Please add your name'); localStorage.setItem('deskos-profile', JSON.stringify({ ...savedProfile, name, location: location || 'Sydney', theme: document.documentElement.dataset.theme || 'lime' })); toast('Your DeskOS is personalised'); setTimeout(() => window.location.reload(), 700); });
