-- DeskOS calendar cloud sync
-- Run this once in the Supabase SQL Editor for your project.

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  local_id text not null,
  title text not null default '',
  date date,
  time text not null default 'All day',
  detail text not null default 'DeskOS event',
  colour text not null default 'purple',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, local_id)
);

alter table public.events enable row level security;

drop policy if exists "Users can view their own events" on public.events;
create policy "Users can view their own events"
on public.events for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can create their own events" on public.events;
create policy "Users can create their own events"
on public.events for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update their own events" on public.events;
create policy "Users can update their own events"
on public.events for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own events" on public.events;
create policy "Users can delete their own events"
on public.events for delete
to authenticated
using (auth.uid() = user_id);

create index if not exists events_user_date_idx on public.events (user_id, date);
